update venue to 株式会社インプレス
FumiyaYoshida/ichiyasaGitSample pull request #1
Opened 2022-04-08 13:53 UTC by FumiyaYoshida

## Update content
Event venue was updated to '株式会社インプレス'.
## Background
'株式会社インプレス' offered event venue.

2022-04-08 15:09 UTC, 238y commented
Nice!
I do merge!

2022-04-09 11:08 UTC, 238y requested changes
Thank you for modifying. Please check and modify.

2022-04-09 11:08 UTC, 238y commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
Please change to 'インプレス株式会社'.

2022-04-09 11:26 UTC, FumiyaYoshida commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
I changed venue to 'インプレス株式会社'.

2022-04-09 11:26 UTC, 238y commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
Thank you!

2022-04-09 11:29 UTC, 238y approved these changes

2022-04-09 11:45 UTC, merged